version: "3.9"
services:
#  mongo:
#    image: mongo
#    ports:
#      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: nodejs-rabbitmq-docker
    hostname: localhost
    ports:
      - 15672:15672
      - 5672:5672